// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package backend

type RegisterUserInput struct {
	Key      string `json:"key"`
	Name     string `json:"name"`
	Password string `json:"password"`
}
